name: Actualitzar temperatures diàriament

on:
  schedule:
    - cron: "59 23 * * *" # Cada dia a les 23:59
  workflow_dispatch: # També es pot executar manualment

jobs:
  update-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositori amb escriptura
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instal·la dependències
        run: |
          pip install requests

      - name: Executa el script meteo.py
        run: |
          python meteo.py

      - name: Pujar fitxer .json al repositori amb PAT
        run: |
          git config user.name "arnauRS13"
          git config user.email "arnauRS13@users.noreply.github.com"
          git add temp_*.json
          git commit -m "Afegit arxiu de temperatura diària" || echo "No hi ha canvis per fer commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
